const quests = [
  {
    id: 'q1',
    title: 'Допомога фермерам',
    type: 'food',
    amount: 15,
    reward: 35,
  },
  {
    id: 'q2',
    title: 'Рубка деревини',
    type: 'wood',
    amount: 25,
    reward: 80,
  },
  {
    id: 'q3',
    title: 'Видобуток руди',
    type: 'ore',
    amount: 20,
    reward: 125,
  },
  {
    id: 'q4',
    title: 'Готування святкового обіду',
    type: 'meal',
    amount: 5,
    reward: 60,
  },
  {
    id: 'q5',
    title: 'Відновлення мосту',
    type: 'planks',
    amount: 10,
    reward: 85,
  },
  {
    id: 'q6',
    title: 'Поставка міді',
    type: 'copper',
    amount: 6,
    reward: 125,
  },
  {
    id: 'q7',
    title: 'Збір заліза для коваля',
    type: 'iron',
    amount: 8,
    reward: 365,
  },
  {
    id: 'q8',
    title: 'Броня зі світлого заліза',
    type: 'whiteIron',
    amount: 4,
    reward: 330,
  },
  {
    id: 'q9',
    title: 'Дослідження кристалу',
    type: 'crystal',
    amount: 2,
    reward: 250,
  },
];
export default quests;
